name: Testing cron

on:
  schedule:
    - cron: '55 * * * *'

jobs:
  call-endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Call Endpoint
        run: curl https://d9c0-149-19-168-214.ngrok-free.app
