name: Testing cron

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  monitor-health-check-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - name: Call Endpoint
        run: |
          node ${{github.workspace}}/monitoring/monitor-app.js test-repo "${{github.environment}}" "${{vars.HEALTHCHECK_URL}}" "${{secrets.GENIE_KEY}}"

  monitor-health-check-stg:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - name: Call Endpoint
        run: |
          node ${{github.workspace}}/monitoring/monitor-app.js test-repo "${{github.environment}}" "${{vars.HEALTHCHECK_URL}}" "${{secrets.GENIE_KEY}}"
