name: Testing cron

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  call-endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Call Endpoint
        run: node ${{github.workspace}}/monitoring/monitor-portal.js "${{vars.HEALTHCHECK_URL}}" "${{secrets.GENIE_KEY}}"
