name: Testing cron

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  monitor-health-check:
    strategy:
      matrix:
        include:
          - environment: development
          - environment: staging
          - environment: production
    runs-on: ubuntu-latest
    environment: ${{matrix.environment}}
    steps:
      - uses: actions/checkout@v3
      - name: Call Endpoint
        run: |
          node ${{github.workspace}}/monitoring/monitor-app.js test-repo "${{matrix.environment}}" "${{vars.HEALTH_CHECK_URL}}" "${{secrets.OPSGENIE_API_KEY}}"
